//===========================================================================
// This source file was generated from CellML by chaste_codegen version (version omitted as unimportant)
//
// Model: aslanidi_model_2009
//
// Processed by chaste_codegen: https://github.com/ModellingWebLab/chaste-codegen
//     (translator: chaste_codegen, model type: RushLarsenLabview)
// on (date omitted as unimportant)
//
// <autogenerated>
//===========================================================================


#include "aslanidi_model_2009.h"

//------------------------------------------------------------------------------

#include <math.h>
#include <string.h>

//------------------------------------------------------------------------------
// State variables
//------------------------------------------------------------------------------

double Y[_NB_OF_STATE_VARIABLES_];
double dY[_NB_OF_STATE_VARIABLES_];
// 0: V (millivolt) (in membrane)
// 1: m (dimensionless) (in sodium_current_m_gate)
// 2: h1 (dimensionless) (in sodium_current_h1_gate)
// 3: h2 (dimensionless) (in sodium_current_h2_gate)
// 4: d_L (dimensionless) (in L_type_Ca_channel_d_L_gate)
// 5: f_L (dimensionless) (in L_type_Ca_channel_f_L_gate)
// 6: d_T (dimensionless) (in T_type_Ca_channel_d_T_gate)
// 7: f_T (dimensionless) (in T_type_Ca_channel_f_T_gate)
// 8: r (dimensionless) (in Ca_independent_transient_outward_K_current_r_gate)
// 9: s1 (dimensionless) (in Ca_independent_transient_outward_K_current_s1_gate)
// 10: s2 (dimensionless) (in Ca_independent_transient_outward_K_current_s2_gate)
// 11: s3 (dimensionless) (in Ca_independent_transient_outward_K_current_s3_gate)
// 12: z (dimensionless) (in delayed_rectifier_K_current_z_gate)
// 13: p_a (dimensionless) (in delayed_rectifier_K_current_pa_gate)
// 14: p_i (dimensionless) (in delayed_rectifier_K_current_pi_gate)
// 15: Na_i (millimolar) (in intracellular_ion_concentrations)
// 16: Ca_i (millimolar) (in intracellular_ion_concentrations)
// 17: K_i (millimolar) (in intracellular_ion_concentrations)
// 18: O_C (dimensionless) (in intracellular_Ca_buffering)
// 19: O_TC (dimensionless) (in intracellular_Ca_buffering)
// 20: O_TMgC (dimensionless) (in intracellular_Ca_buffering)
// 21: O_TMgMg (dimensionless) (in intracellular_Ca_buffering)
// 22: K_c (millimolar) (in cleft_space_ion_concentrations)
// 23: Ca_rel (millimolar) (in Ca_handling_by_the_SR)
// 24: Ca_up (millimolar) (in Ca_handling_by_the_SR)
// 25: O_Calse (dimensionless) (in Ca_handling_by_the_SR)
// 26: F1 (dimensionless) (in Ca_handling_by_the_SR)
// 27: F2 (dimensionless) (in Ca_handling_by_the_SR)
// 28: F3 (dimensionless) (in Ca_handling_by_the_SR)

char YNames[_NB_OF_STATE_VARIABLES_][8];
char YUnits[_NB_OF_STATE_VARIABLES_][14];
char YComponents[_NB_OF_STATE_VARIABLES_][51];

//------------------------------------------------------------------------------
// Constants
//------------------------------------------------------------------------------

double A0_bck; // dimensionless (in A0_bc)
double Ampl_gain; // dimensionless (in Ampl_gai)
double Cext; // picoF (in Cex)
double E_l; // millivolt (in E_)
double I; // dimensionless (in )
double R_seal; // ohm (in R_sea)
double Scale_bck; // dimensionless (in Scale_bc)
double Scaling; // dimensionless (in Scalin)
double k_bck; // one_over_millivolt (in k_bc)
double leak_comp_perc; // dimensionless (in leak_comp_per)
double Cm; // nanoF (in membrane)
double stim_amplitude; // picoA (in membrane)
double stim_duration; // second (in membrane)
double stim_start; // second (in membrane)
double stim_period; // second (in membrane)

double A0_bck; // dimensionless (in A0_bc)
double Ampl_gain; // dimensionless (in Ampl_gai)
double I_up_max; // picoA (in Ca_handling_by_the_SR)
double Vol_rel; // nanolitre (in Ca_handling_by_the_SR)
double Vol_up; // nanolitre (in Ca_handling_by_the_SR)
double alpha_rel; // picoA_per_millimolar (in Ca_handling_by_the_SR)
double k_F3; // per_second (in Ca_handling_by_the_SR)
double k_cyca; // millimolar (in Ca_handling_by_the_SR)
double k_rel; // millimolar (in Ca_handling_by_the_SR)
double k_srca; // millimolar (in Ca_handling_by_the_SR)
double k_xcs; // dimensionless (in Ca_handling_by_the_SR)
double tau_tr; // second (in Ca_handling_by_the_SR)
double g_to; // nanoS (in Ca_independent_transient_outward_K_current)
double Cext; // picoF (in Cex)
double E_l; // millivolt (in E_)
double I; // dimensionless (in )
double E_Ca_app; // millivolt (in L_type_Ca_channel)
double g_Ca_L; // nanoS (in L_type_Ca_channel)
double d_NaCa; // per_millimolar_4 (in Na_Ca_ion_exchanger_current)
double gamma; // dimensionless (in Na_Ca_ion_exchanger_current)
double k_NaCa; // picoA_per_millimolar_4 (in Na_Ca_ion_exchanger_current)
double R_seal; // ohm (in R_sea)
double Scale_bck; // dimensionless (in Scale_bc)
double Scaling; // dimensionless (in Scalin)
double E_Ca_T; // millivolt (in T_type_Ca_channel)
double g_Ca_T; // nanoS (in T_type_Ca_channel)
double g_B_Ca; // nanoS (in background_currents)
double g_B_Na; // nanoS (in background_currents)
double Ca_c; // millimolar (in cleft_space_ion_concentrations)
double Na_c; // millimolar (in cleft_space_ion_concentrations)
double Vol_c; // nanolitre (in cleft_space_ion_concentrations)
double g_Kr; // nanoS (in delayed_rectifier_K_current)
double g_Ks; // nanoS (in delayed_rectifier_K_current)
double CT; // dimensionless (in environment)
double Mg_i; // millimolar (in intracellular_Ca_buffering)
double Vol_Ca; // nanolitre (in intracellular_ion_concentrations)
double Vol_i; // nanolitre (in intracellular_ion_concentrations)
double KmK1; // millimolar (in inward_rectifier)
double g_K1; // nanoS (in inward_rectifier)
double shiftK1; // millivolt (in inward_rectifier)
double steepK1; // dimensionless (in inward_rectifier)
double k_bck; // one_over_millivolt (in k_bc)
double leak_comp_perc; // dimensionless (in leak_comp_per)
double F; // coulomb_per_mole (in membrane)
double R; // millijoule_per_mole_kelvin (in membrane)
double T; // kelvin (in membrane)
double stim_end; // second (in membrane)
double i_CaP_max; // picoA (in sarcolemmal_calcium_pump_current)
double k_CaP; // millimolar (in sarcolemmal_calcium_pump_current)
double i_NaK_max; // picoA (in sodium_potassium_pump)
double k_NaK_K; // millimolar (in sodium_potassium_pump)
double k_NaK_Na; // millimolar (in sodium_potassium_pump)

//------------------------------------------------------------------------------
// Computed variables
//------------------------------------------------------------------------------

double O_Calse_orig_deriv; // 1 / second (in Ca_handling_by_the_SR)
double I_ext; // dimensionless (in I_ex)
double PM; // dimensionless (in environment)
double time; // second (in environment)
double g_leak; // one_over_ohm (in g_lea)
double O_TMgMg_orig_deriv; // 1 / second (in intracellular_Ca_buffering)
double i_rel; // picoA (in Ca_handling_by_the_SR)
double i_up; // picoA (in Ca_handling_by_the_SR)
double r_inact; // per_second (in Ca_handling_by_the_SR)
double F3_orig_deriv; // 1 / second (in Ca_handling_by_the_SR)
double dOCdt; // per_second (in intracellular_Ca_buffering)
double O_C_orig_deriv; // 1 / second (in intracellular_Ca_buffering)
double dOTCdt; // per_second (in intracellular_Ca_buffering)
double O_TC_orig_deriv; // 1 / second (in intracellular_Ca_buffering)
double dOTMgCdt; // per_second (in intracellular_Ca_buffering)
double O_TMgC_orig_deriv; // 1 / second (in intracellular_Ca_buffering)
double i_tr; // picoA (in Ca_handling_by_the_SR)
double Ca_rel_orig_deriv; // millimolar / second (in Ca_handling_by_the_SR)
double Ca_up_orig_deriv; // millimolar / second (in Ca_handling_by_the_SR)
double E_K; // millivolt (in Ca_independent_transient_outward_K_current)
double E_Ca; // millivolt (in background_currents)
double r_act; // per_second (in Ca_handling_by_the_SR)
double F1_orig_deriv; // 1 / second (in Ca_handling_by_the_SR)
double F2_orig_deriv; // 1 / second (in Ca_handling_by_the_SR)
double i_sus; // picoA (in Ca_independent_transient_outward_K_current)
double i_to; // picoA (in Ca_independent_transient_outward_K_current)
double alpha_r; // per_second (in Ca_independent_transient_outward_K_current_r_gate)
double beta_r; // per_second (in Ca_independent_transient_outward_K_current_r_gate)
double r_infinity; // dimensionless (in Ca_independent_transient_outward_K_current_r_gate)
double tau_r; // second (in Ca_independent_transient_outward_K_current_r_gate)
double r_orig_deriv; // 1 / second (in Ca_independent_transient_outward_K_current_r_gate)
double s1_infinity; // dimensionless (in Ca_independent_transient_outward_K_current_s1_gate)
double tau_s1; // second (in Ca_independent_transient_outward_K_current_s1_gate)
double s1_orig_deriv; // 1 / second (in Ca_independent_transient_outward_K_current_s1_gate)
double s2_infinity; // dimensionless (in Ca_independent_transient_outward_K_current_s2_gate)
double tau_s2; // second (in Ca_independent_transient_outward_K_current_s2_gate)
double s2_orig_deriv; // 1 / second (in Ca_independent_transient_outward_K_current_s2_gate)
double s3_infinity; // dimensionless (in Ca_independent_transient_outward_K_current_s3_gate)
double tau_s3; // second (in Ca_independent_transient_outward_K_current_s3_gate)
double s3_orig_deriv; // 1 / second (in Ca_independent_transient_outward_K_current_s3_gate)
double d_prime; // dimensionless (in L_type_Ca_channel)
double i_Ca_L; // picoA (in L_type_Ca_channel)
double E10; // millivolt (in L_type_Ca_channel_d_L_gate)
double alpha_d_L; // per_second (in L_type_Ca_channel_d_L_gate)
double beta_d_L; // per_second (in L_type_Ca_channel_d_L_gate)
double d_L_infinity; // dimensionless (in L_type_Ca_channel_d_L_gate)
double tau_d_L; // second (in L_type_Ca_channel_d_L_gate)
double d_L_orig_deriv; // 1 / second (in L_type_Ca_channel_d_L_gate)
double E0_f_L; // millivolt (in L_type_Ca_channel_f_L_gate)
double alpha_f_L; // per_second (in L_type_Ca_channel_f_L_gate)
double beta_f_L; // per_second (in L_type_Ca_channel_f_L_gate)
double f_L_infinity; // dimensionless (in L_type_Ca_channel_f_L_gate)
double tau_f_L; // second (in L_type_Ca_channel_f_L_gate)
double f_L_orig_deriv; // 1 / second (in L_type_Ca_channel_f_L_gate)
double i_NaCa; // picoA (in Na_Ca_ion_exchanger_current)
double i_Ca_T; // picoA (in T_type_Ca_channel)
double E0_d_T; // millivolt (in T_type_Ca_channel_d_T_gate)
double alpha_d_T; // per_second (in T_type_Ca_channel_d_T_gate)
double beta_d_T; // per_second (in T_type_Ca_channel_d_T_gate)
double d_T_infinity; // dimensionless (in T_type_Ca_channel_d_T_gate)
double tau_d_T; // second (in T_type_Ca_channel_d_T_gate)
double d_T_orig_deriv; // 1 / second (in T_type_Ca_channel_d_T_gate)
double E0_f_T; // millivolt (in T_type_Ca_channel_f_T_gate)
double alpha_f_T; // per_second (in T_type_Ca_channel_f_T_gate)
double beta_f_T; // per_second (in T_type_Ca_channel_f_T_gate)
double f_T_infinity; // dimensionless (in T_type_Ca_channel_f_T_gate)
double tau_f_T; // second (in T_type_Ca_channel_f_T_gate)
double f_T_orig_deriv; // 1 / second (in T_type_Ca_channel_f_T_gate)
double i_B_Ca; // picoA (in background_currents)
double i_Kr; // picoA (in delayed_rectifier_K_current)
double i_Ks; // picoA (in delayed_rectifier_K_current)
double alpha_p_a; // per_second (in delayed_rectifier_K_current_pa_gate)
double beta_p_a; // per_second (in delayed_rectifier_K_current_pa_gate)
double p_a_infinity; // dimensionless (in delayed_rectifier_K_current_pa_gate)
double tau_p_a; // second (in delayed_rectifier_K_current_pa_gate)
double p_a_orig_deriv; // 1 / second (in delayed_rectifier_K_current_pa_gate)
double alpha_p_i; // per_second (in delayed_rectifier_K_current_pi_gate)
double beta_p_i; // per_second (in delayed_rectifier_K_current_pi_gate)
double p_i_infinity; // dimensionless (in delayed_rectifier_K_current_pi_gate)
double tau_p_i; // second (in delayed_rectifier_K_current_pi_gate)
double p_i_orig_deriv; // 1 / second (in delayed_rectifier_K_current_pi_gate)
double alpha_z; // per_second (in delayed_rectifier_K_current_z_gate)
double beta_z; // per_second (in delayed_rectifier_K_current_z_gate)
double tau_z; // second (in delayed_rectifier_K_current_z_gate)
double z_infinity; // dimensionless (in delayed_rectifier_K_current_z_gate)
double z_orig_deriv; // 1 / second (in delayed_rectifier_K_current_z_gate)
double i_bck; // dimensionless (in i_bc)
double i_leak_comp; // dimensionless (in i_leak_com)
double i_inj; // dimensionless (in i_in)
double i_K1; // picoA (in inward_rectifier)
double i_Stim; // picoA (in membrane)
double i_CaP; // picoA (in sarcolemmal_calcium_pump_current)
double Ca_i_orig_deriv; // millimolar / second (in intracellular_ion_concentrations)
double E_Na; // millivolt (in sodium_current)
double i_B_Na; // picoA (in background_currents)
double alpha_h; // per_second (in sodium_current_h1_gate)
double beta_h; // per_second (in sodium_current_h1_gate)
double h_infinity; // dimensionless (in sodium_current_h1_gate)
double tau_h1; // second (in sodium_current_h1_gate)
double h1_orig_deriv; // 1 / second (in sodium_current_h1_gate)
double tau_h2; // second (in sodium_current_h2_gate)
double h2_orig_deriv; // 1 / second (in sodium_current_h2_gate)
double E0_m; // millivolt (in sodium_current_m_gate)
double alpha_m; // per_second (in sodium_current_m_gate)
double beta_m; // per_second (in sodium_current_m_gate)
double i_Na; // picoA (in sodium_current)
double m_orig_deriv; // 1 / second (in sodium_current_m_gate)
double i_p; // picoA (in sodium_potassium_pump)
double K_c_orig_deriv; // millimolar / second (in cleft_space_ion_concentrations)
double K_i_orig_deriv; // millimolar / second (in intracellular_ion_concentrations)
double Na_i_orig_deriv; // millimolar / second (in intracellular_ion_concentrations)
double V_orig_deriv; // millivolt / second (in membrane)


//------------------------------------------------------------------------------
// Initialisation
//------------------------------------------------------------------------------

void init()
{
    //---------------------------------------------------------------------------
    // State variables
    //---------------------------------------------------------------------------

    Y[0] = -80.0; // V (millivolt) (in membrane)
    Y[1] = 0.01309; // m (dimensionless) (in sodium_current_m_gate)
    Y[2] = 0.706; // h1 (dimensionless) (in sodium_current_h1_gate)
    Y[3] = 0.61493; // h2 (dimensionless) (in sodium_current_h2_gate)
    Y[4] = 3e-05; // d_L (dimensionless) (in L_type_Ca_channel_d_L_gate)
    Y[5] = 0.99981; // f_L (dimensionless) (in L_type_Ca_channel_f_L_gate)
    Y[6] = 0.00046; // d_T (dimensionless) (in T_type_Ca_channel_d_T_gate)
    Y[7] = 0.30752; // f_T (dimensionless) (in T_type_Ca_channel_f_T_gate)
    Y[8] = 6e-05; // r (dimensionless) (in Ca_independent_transient_outward_K_current_r_gate)
    Y[9] = 0.5753; // s1 (dimensionless) (in Ca_independent_transient_outward_K_current_s1_gate)
    Y[10] = 0.39871; // s2 (dimensionless) (in Ca_independent_transient_outward_K_current_s2_gate)
    Y[11] = 0.57363; // s3 (dimensionless) (in Ca_independent_transient_outward_K_current_s3_gate)
    Y[12] = 0.02032; // z (dimensionless) (in delayed_rectifier_K_current_z_gate)
    Y[13] = 0.00016; // p_a (dimensionless) (in delayed_rectifier_K_current_pa_gate)
    Y[14] = 0.76898; // p_i (dimensionless) (in delayed_rectifier_K_current_pi_gate)
    Y[15] = 8.4; // Na_i (millimolar) (in intracellular_ion_concentrations)
    Y[16] = 7.1e-05; // Ca_i (millimolar) (in intracellular_ion_concentrations)
    Y[17] = 100.0; // K_i (millimolar) (in intracellular_ion_concentrations)
    Y[18] = 0.029108; // O_C (dimensionless) (in intracellular_Ca_buffering)
    Y[19] = 0.014071; // O_TC (dimensionless) (in intracellular_Ca_buffering)
    Y[20] = 0.214036; // O_TMgC (dimensionless) (in intracellular_Ca_buffering)
    Y[21] = 0.693565; // O_TMgMg (dimensionless) (in intracellular_Ca_buffering)
    Y[22] = 5.0; // K_c (millimolar) (in cleft_space_ion_concentrations)
    Y[23] = 0.726776; // Ca_rel (millimolar) (in Ca_handling_by_the_SR)
    Y[24] = 0.730866; // Ca_up (millimolar) (in Ca_handling_by_the_SR)
    Y[25] = 0.465921; // O_Calse (dimensionless) (in Ca_handling_by_the_SR)
    Y[26] = 0.288039; // F1 (dimensionless) (in Ca_handling_by_the_SR)
    Y[27] = 0.002262; // F2 (dimensionless) (in Ca_handling_by_the_SR)
    Y[28] = 0.612697; // F3 (dimensionless) (in Ca_handling_by_the_SR)

    strcpy(YNames[0], "V");
    strcpy(YNames[1], "m");
    strcpy(YNames[2], "h1");
    strcpy(YNames[3], "h2");
    strcpy(YNames[4], "d_L");
    strcpy(YNames[5], "f_L");
    strcpy(YNames[6], "d_T");
    strcpy(YNames[7], "f_T");
    strcpy(YNames[8], "r");
    strcpy(YNames[9], "s1");
    strcpy(YNames[10], "s2");
    strcpy(YNames[11], "s3");
    strcpy(YNames[12], "z");
    strcpy(YNames[13], "p_a");
    strcpy(YNames[14], "p_i");
    strcpy(YNames[15], "Na_i");
    strcpy(YNames[16], "Ca_i");
    strcpy(YNames[17], "K_i");
    strcpy(YNames[18], "O_C");
    strcpy(YNames[19], "O_TC");
    strcpy(YNames[20], "O_TMgC");
    strcpy(YNames[21], "O_TMgMg");
    strcpy(YNames[22], "K_c");
    strcpy(YNames[23], "Ca_rel");
    strcpy(YNames[24], "Ca_up");
    strcpy(YNames[25], "O_Calse");
    strcpy(YNames[26], "F1");
    strcpy(YNames[27], "F2");
    strcpy(YNames[28], "F3");

    strcpy(YUnits[0], "millivolt");
    strcpy(YUnits[1], "dimensionless");
    strcpy(YUnits[2], "dimensionless");
    strcpy(YUnits[3], "dimensionless");
    strcpy(YUnits[4], "dimensionless");
    strcpy(YUnits[5], "dimensionless");
    strcpy(YUnits[6], "dimensionless");
    strcpy(YUnits[7], "dimensionless");
    strcpy(YUnits[8], "dimensionless");
    strcpy(YUnits[9], "dimensionless");
    strcpy(YUnits[10], "dimensionless");
    strcpy(YUnits[11], "dimensionless");
    strcpy(YUnits[12], "dimensionless");
    strcpy(YUnits[13], "dimensionless");
    strcpy(YUnits[14], "dimensionless");
    strcpy(YUnits[15], "millimolar");
    strcpy(YUnits[16], "millimolar");
    strcpy(YUnits[17], "millimolar");
    strcpy(YUnits[18], "dimensionless");
    strcpy(YUnits[19], "dimensionless");
    strcpy(YUnits[20], "dimensionless");
    strcpy(YUnits[21], "dimensionless");
    strcpy(YUnits[22], "millimolar");
    strcpy(YUnits[23], "millimolar");
    strcpy(YUnits[24], "millimolar");
    strcpy(YUnits[25], "dimensionless");
    strcpy(YUnits[26], "dimensionless");
    strcpy(YUnits[27], "dimensionless");
    strcpy(YUnits[28], "dimensionless");

    //------------------------------------------------------------------------------
    // Constants
    //------------------------------------------------------------------------------

    A0_bck = 1.0278;
    Ampl_gain = 1.0;
    Cext = 1.0;
    E_l = 1.0;
    I = 1.0;
    R_seal = 1.0;
    Scale_bck = 1.0;
    Scaling = 1.0;
    k_bck = 0.098599999999999993;
    leak_comp_perc = 1.0;
    Cm = 5.0000000000000002e-5;
    stim_amplitude = -20.0;
    stim_duration = 0.00020000000000000001;
    stim_start = 0.01;
    stim_period = 0.5;

    A0_bck = 1.0278;
    Ampl_gain = 1.0;
    I_up_max = 2.7999999999999998;
    Vol_rel = 4.3999999999999997e-8;
    Vol_up = 3.9690000000000001e-7;
    alpha_rel = 200.0;
    k_F3 = 0.81499999999999995;
    k_cyca = 0.00029999999999999997;
    k_rel = 0.00029999999999999997;
    k_srca = 0.5;
    k_xcs = 0.40000000000000002;
    tau_tr = 0.01;
    g_to = 0.050001999999999998;
    Cext = 1.0;
    E_l = 1.0;
    I = 1.0;
    E_Ca_app = 50.0;
    g_Ca_L = 0.0040000000000000001;
    d_NaCa = 0.00029999999999999997;
    gamma = 0.45000000000000001;
    k_NaCa = 2.0000000000000002e-5;
    R_seal = 1.0;
    Scale_bck = 1.0;
    Scaling = 1.0;
    E_Ca_T = 38.0;
    g_Ca_T = 0.0060000000000000001;
    g_B_Ca = 3.1000000000000001e-5;
    g_B_Na = 6.3999999999999997e-5;
    Ca_c = 2.5;
    Na_c = 140.0;
    Vol_c = 2.5000000000000002e-6;
    g_Kr = 0.0035000000000000001;
    g_Ks = 0.0025000000000000001;
    CT = 1.0;
    Mg_i = 2.5;
    Vol_Ca = 5.8839999999999999e-6;
    Vol_i = 1.26e-5;
    KmK1 = 0.58999999999999997;
    g_K1 = 0.0050800000000000003;
    shiftK1 = -3.6000000000000001;
    steepK1 = 1.393;
    k_bck = 0.098599999999999993;
    leak_comp_perc = 1.0;
    F = 96487.0;
    R = 8314.0;
    T = 308.0;
    stim_end = 100.0;
    i_CaP_max = 0.0095090000000000001;
    k_CaP = 0.00020000000000000001;
    i_NaK_max = 0.064409999999999995;
    k_NaK_K = 1.0;
    k_NaK_Na = 11.0;

}

void compute(double time_converted)
{
   // time: time_converted (millisecond)

    O_Calse_orig_deriv = -400.0 * Y[25] + 480.0 * (1.0 - Y[25]) * Y[23];
    dY[25] = 0.001 * O_Calse_orig_deriv;
    I_ext = I / (Ampl_gain * Cext);
    PM = 0;
    time = 0.001 * Y[29];
    g_leak = 1 / R_seal;
    O_TMgMg_orig_deriv = -666.0 * Y[21] + 2000.0 * (1.0 - Y[20] - Y[21]) * Mg_i;
    dY[21] = 0.001 * O_TMgMg_orig_deriv;
    i_rel = pow(Y[27], 2) * (-Y[16] + Y[23]) * alpha_rel / pow((0.25 + Y[27]), 2);
    i_up = (Y[16] / k_cyca - pow(k_xcs, 2) * Y[24] / k_srca) * I_up_max / ((k_cyca + Y[16]) / k_cyca + (k_srca + Y[24]) * k_xcs / k_srca);
    r_inact = 33.960000000000001 + 339.60000000000002 * pow(Y[16], 4) / pow((k_rel + Y[16]), 4);
    F3_orig_deriv = r_inact * Y[27] - k_F3 * Y[28];
    dY[28] = 0.001 * F3_orig_deriv;
    dOCdt = -476.0 * Y[18] + 200000.0 * (1.0 - Y[18]) * Y[16];
    O_C_orig_deriv = dOCdt;
    dY[18] = 0.001 * O_C_orig_deriv;
    dOTCdt = -392.0 * Y[19] + 78400.0 * (1.0 - Y[19]) * Y[16];
    O_TC_orig_deriv = dOTCdt;
    dY[19] = 0.001 * O_TC_orig_deriv;
    dOTMgCdt = -6.5999999999999996 * Y[20] + 200000.0 * (1.0 - Y[20] - Y[21]) * Y[16];
    O_TMgC_orig_deriv = dOTMgCdt;
    dY[20] = 0.001 * O_TMgC_orig_deriv;
    i_tr = 2.0 * (-Y[23] + Y[24]) * Vol_rel * F / tau_tr;
    Ca_rel_orig_deriv = -31.0 * O_Calse_orig_deriv + 0.5 * (-i_rel + i_tr) / (Vol_rel * F);
    Ca_up_orig_deriv = 0.5 * (-i_tr + i_up) / (Vol_up * F);
    dY[23] = 0.001 * Ca_rel_orig_deriv;
    dY[24] = 0.001 * Ca_up_orig_deriv;
    E_K = R * T * log(Y[22] / Y[17]) / F;
    E_Ca = 0.5 * R * T * log(Ca_c / Y[16]) / F;
    r_act = 240.0 * exp(-1.6000000000000001 + 0.080000000000000002 * Y[0]) + 203.80000000000001 * pow(Y[16], 4) / pow((k_rel + Y[16]), 4);
    F1_orig_deriv = k_F3 * Y[28] - r_act * Y[26];
    F2_orig_deriv = r_act * Y[26] - r_inact * Y[27];
    if ((CT == 1.0) && (PM == 0))
        i_sus = 0.098000000000000004 + 0.0014 * Y[0]
    else if ((CT == 0) && (PM == 1.0))
        i_sus = 0.16799999999999998 + 0.0023999999999999998 * Y[0]
    else 
        i_sus = 0.070000000000000007 + 0.001 * Y[0]

    if ((CT == 1.0) && (PM == 0))
        i_to = 0.20000000000000001 * (0.40000000000000002 + 0.59999999999999998 * pow(Y[11], 6)) * (-E_K + Y[0]) * (0.58999999999999997 * pow(Y[9], 3) + 0.40999999999999998 * pow(Y[10], 3)) * g_to * Y[8]
    else if ((CT == 0) && (PM == 1.0))
        i_to = 0.34999999999999998 * (0.40000000000000002 + 0.59999999999999998 * pow(Y[11], 6)) * (-E_K + Y[0]) * (0.58999999999999997 * pow(Y[9], 3) + 0.40999999999999998 * pow(Y[10], 3)) * g_to * Y[8]
    else 
        i_to = (0.40000000000000002 + 0.59999999999999998 * pow(Y[11], 6)) * (-E_K + Y[0]) * (0.58999999999999997 * pow(Y[9], 3) + 0.40999999999999998 * pow(Y[10], 3)) * g_to * Y[8]

    alpha_r = 386.60000000000002 * exp(0.083333333333333329 * Y[0]);
    beta_r = 8.0109999999999992 * exp(-0.1388888888888889 * Y[0]);
    r_infinity = 1 / (1.0 + exp(-2.6628794603230959 - 0.17752529735487307 * Y[0]));
    tau_r = 0.00040000000000000002 + 1 / (alpha_r + beta_r);
    r_orig_deriv = (-Y[8] + r_infinity) / tau_r;
    s1_infinity = 1 / (1.0 + exp(4.0070821529745047 + 0.14164305949008499 * Y[0]));
    tau_s1 = 0.020400000000000001 + 0.54659999999999997 / (1.0 + exp(327.99999999999994 + 10.0 * Y[0]));
    s1_orig_deriv = (-Y[9] + s1_infinity) / tau_s1;
    s2_infinity = 1 / (1.0 + exp(4.0070821529745047 + 0.14164305949008499 * Y[0]));
    tau_s2 = 5.75 / (1.0 + exp(327.99999999999994 + 10.0 * Y[0])) + 0.45000000000000001 / (1.0 + exp(0.96921975662133131 - 0.071581961345740866 * Y[0]));
    s2_orig_deriv = (-Y[10] + s2_infinity) / tau_s2;
    s3_infinity = 0.39975990396158467 + 0.60024009603841544 / (1.0 + exp(1.8506208911614319 + 0.036523009495982472 * Y[0]));
    tau_s3 = 0.5 + 7.5 / (1.0 + exp(46.0 + 2.0 * Y[0]));
    s3_orig_deriv = (-Y[11] + s3_infinity) / tau_s3;
    dY[26] = 0.001 * F1_orig_deriv;
    dY[27] = 0.001 * F2_orig_deriv;
    dY[8] = 0.001 * r_orig_deriv;
    dY[9] = 0.001 * s1_orig_deriv;
    dY[10] = 0.001 * s2_orig_deriv;
    dY[11] = 0.001 * s3_orig_deriv;
    d_prime = 1 / (1.0 + exp(1.9166666666666667 - 0.083333333333333329 * Y[0]));
    if ((CT == 1.0) && (PM == 0))
        i_Ca_L = 1.8 * (-E_Ca_app + Y[0]) * (Y[4] * Y[5] + d_prime) * g_Ca_L
    else if ((CT == 0) && (PM == 1.0))
        i_Ca_L = 2.1000000000000001 * (-E_Ca_app + Y[0]) * (Y[4] * Y[5] + d_prime) * g_Ca_L
    else 
        i_Ca_L = (-E_Ca_app + Y[0]) * (Y[4] * Y[5] + d_prime) * g_Ca_L

    E10 = 10.0 + Y[0];
    alpha_d_L = ((abs(10.0 + Y[0]) < 4.8080000000089163e-7) ? (-2.4039999999697637e-5 / (-1.0 + exp(-9.9999999998742257e-8)) - 1039933.4442576389 * (9.9999995191999993 + Y[0]) * (2.4040000000391526e-5 / (-1.0 + exp(1.0000000000162864e-7)) + 2.4039999999697637e-5 / (-1.0 + exp(-9.9999999998742257e-8)))) : (-50.0 * (10.0 + Y[0]) / (-1.0 + exp(-2.0798668885191347 - 0.20798668885191349 * Y[0])))) + ((abs(45.0 + Y[0]) < 2.5000000000718892e-7) ? (-4.1800000005842713e-6 / (-1.0 + exp(-1.000000000139778e-7)) - 1999999.9999424887 * (44.999999750000001 + Y[0]) * (4.1800000005842713e-6 / (-1.0 + exp(-1.000000000139778e-7)) + 4.1799999996561256e-6 / (-1.0 + exp(9.9999999991773334e-8)))) : (-16.719999999999999 * (45.0 + Y[0]) / (-1.0 + exp(-18.0 - 0.40000000000000002 * Y[0]))));
    if (abs(5.0 + Y[0]) < 2.5000000000025002e-7)
        beta_d_L = -1.1200000000011203e-6 / (-1.0 + exp(-1.0000000000010001e-7)) + 1999999.9999979998 * (5.0000002500000003 + Y[0]) * (1.1200000000011203e-6 / (-1.0 + exp(1.0000000000010001e-7)) + 1.1200000000011203e-6 / (-1.0 + exp(-1.0000000000010001e-7)))
    else 
        beta_d_L = 4.4800000000000004 * (5.0 + Y[0]) / (-1.0 + exp(2.0 + 0.40000000000000002 * Y[0]))

    d_L_infinity = 1 / (1.0 + exp(-0.14393939393939395 - 0.15151515151515152 * E10));
    tau_d_L = 1 / (alpha_d_L + beta_d_L);
    d_L_orig_deriv = (-Y[4] + d_L_infinity) / tau_d_L;
    dY[4] = 0.001 * d_L_orig_deriv;
    E0_f_L = 18.0 + Y[0];
    if (abs(18.0 + Y[0]) < 4.0000000001150227e-7)
        alpha_f_L = -3.3960000000976542e-6 / (-1.0 + exp(-1.0000000000287557e-7)) + 1249999.9999640554 * (18.000000400000001 + Y[0]) * (3.3960000000976542e-6 / (-1.0 + exp(1.0000000000287557e-7)) + 3.3960000000976542e-6 / (-1.0 + exp(-1.0000000000287557e-7)))
    else 
        alpha_f_L = 8.4900000000000002 * (18.0 + Y[0]) / (-1.0 + exp(4.5 + 0.25 * Y[0]))

    beta_f_L = 67.921999999999997 / (1.0 + exp(-0.25 * E0_f_L));
    f_L_infinity = alpha_f_L / (alpha_f_L + beta_f_L);
    tau_f_L = 1 / (alpha_f_L + beta_f_L);
    f_L_orig_deriv = (-Y[5] + f_L_infinity) / tau_f_L;
    dY[5] = 0.001 * f_L_orig_deriv;
    i_NaCa = (pow(Y[15], 3) * Ca_c * exp(gamma * Y[0] * F / (R * T)) - pow(Na_c, 3) * Y[16] * exp((-1.0 + gamma) * Y[0] * F / (R * T))) * k_NaCa / (1.0 + (pow(Y[15], 3) * Ca_c + pow(Na_c, 3) * Y[16]) * d_NaCa);
    i_Ca_T = (-E_Ca_T + Y[0]) * g_Ca_T * Y[6] * Y[7];
    E0_d_T = 23.300000000000001 + Y[0];
    alpha_d_T = 674.173 * exp(0.033333333333333333 * E0_d_T);
    beta_d_T = 674.173 * exp(-0.033333333333333333 * E0_d_T);
    d_T_infinity = 1 / (1.0 + exp(0.049180327868852458 - 0.16393442622950821 * E0_d_T));
    tau_d_T = 1 / (alpha_d_T + beta_d_T);
    d_T_orig_deriv = (-Y[6] + d_T_infinity) / tau_d_T;
    dY[6] = 0.001 * d_T_orig_deriv;
    E0_f_T = 75.0 + Y[0];
    alpha_f_T = 9.6370000000000005 * exp(-0.012004801920768308 * E0_f_T);
    beta_f_T = 9.6370000000000005 * exp(0.065019505851755519 * E0_f_T);
    f_T_infinity = alpha_f_T / (alpha_f_T + beta_f_T);
    tau_f_T = 1 / (alpha_f_T + beta_f_T);
    f_T_orig_deriv = (-Y[7] + f_T_infinity) / tau_f_T;
    dY[7] = 0.001 * f_T_orig_deriv;
    if ((CT == 1.0) && (PM == 0))
        i_B_Ca = 2.0000000000000002e-5 * Y[0] - 2.0000000000000002e-5 * E_Ca
    else if ((CT == 0) && (PM == 1.0))
        i_B_Ca = 3.0000000000000001e-5 * Y[0] - 3.0000000000000001e-5 * E_Ca
    else 
        i_B_Ca = (-E_Ca + Y[0]) * g_B_Ca

    i_Kr = (-E_K + Y[0]) * Y[13] * Y[14] * g_Kr;
    i_Ks = (-E_K + Y[0]) * Y[12] * g_Ks;
    alpha_p_a = 9.0 * exp(0.03941508020968823 * Y[0]);
    beta_p_a = 1.3 * exp(-0.076769537847382163 * Y[0]);
    p_a_infinity = 1 / (1.0 + exp(-0.68918918918918914 - 0.13513513513513511 * Y[0]));
    tau_p_a = 1 / (alpha_p_a + beta_p_a);
    p_a_orig_deriv = (-Y[13] + p_a_infinity) / tau_p_a;
    dY[13] = 0.001 * p_a_orig_deriv;
    alpha_p_i = 100.0 * exp(-0.018299935950224173 * Y[0]);
    beta_p_i = 656.0 * exp(0.009420009985210585 * Y[0]);
    p_i_infinity = 1 / (1.0 + exp(2.539728728905752 + 0.05358970648917756 * Y[0]));
    tau_p_i = 1 / (alpha_p_i + beta_p_i);
    p_i_orig_deriv = (-Y[14] + p_i_infinity) / tau_p_i;
    dY[14] = 0.001 * p_i_orig_deriv;
    alpha_z = 1.6599999999999999 * exp(0.014398433450440593 * Y[0]);
    beta_z = 0.29999999999999999 * exp(-0.045816915605241454 * Y[0]);
    tau_z = 0.059999999999999998 + 1 / (alpha_z + beta_z);
    z_infinity = 1 / (1.0 + exp(0.065217391304347824 - 0.072463768115942032 * Y[0]));
    z_orig_deriv = (-Y[12] + z_infinity) / tau_z;
    dY[12] = 0.001 * z_orig_deriv;
    i_bck = A0_bck * Scale_bck / ((1 + exp(-Y[0] * k_bck)) * Cext);
    i_leak_comp = (-E_l + Y[0]) * g_leak * leak_comp_perc / (100 * Cext);
    i_inj = (-i_bck - i_leak_comp + I_ext) * Scaling;
    if ((CT == 1.0) && (PM == 0))
        i_K1 = 2.0 * pow(Y[22], 3) * (-E_K + Y[0]) * g_K1 / ((1.0 + exp((-E_K - shiftK1 + Y[0]) * steepK1 * F / (R * T))) * pow((Y[22] + KmK1), 3))
    else if ((CT == 0) && (PM == 1.0))
        i_K1 = 2.5 * pow(Y[22], 3) * (-E_K + Y[0]) * g_K1 / ((1.0 + exp((-E_K - shiftK1 + Y[0]) * steepK1 * F / (R * T))) * pow((Y[22] + KmK1), 3))
    else 
        i_K1 = pow(Y[22], 3) * (-E_K + Y[0]) * g_K1 / ((1.0 + exp((-E_K - shiftK1 + Y[0]) * steepK1 * F / (R * T))) * pow((Y[22] + KmK1), 3))

    if ((time >= stim_start) && (time <= stim_end) && (stim_duration >= -stim_start - stim_period * floor((-stim_start + time) / stim_period) + time))
        i_Stim = stim_amplitude
    else 
        i_Stim = 0

    i_CaP = Y[16] * i_CaP_max / (Y[16] + k_CaP);
    Ca_i_orig_deriv = -0.044999999999999998 * dOCdt - 0.080000000000000002 * dOTCdt - 0.16 * dOTMgCdt + 0.5 * (-i_up - i_Ca_L - i_Ca_T - i_B_Ca - i_CaP + 2.0 * i_NaCa + i_rel) / (Vol_Ca * F);
    dY[16] = 0.001 * Ca_i_orig_deriv;
    E_Na = R * T * log(Na_c / Y[15]) / F;
    if ((CT == 1.0) && (PM == 0))
        i_B_Na = 2.0000000000000002e-5 * Y[0] - 2.0000000000000002e-5 * E_Na
    else if ((CT == 0) && (PM == 1.0))
        i_B_Na = 3.0000000000000001e-5 * Y[0] - 3.0000000000000001e-5 * E_Na
    else 
        i_B_Na = (-E_Na + Y[0]) * g_B_Na

    alpha_h = 44.899999999999999 * exp(-12.010771992818672 - 0.17953321364452424 * Y[0]);
    beta_h = 1491.0 / (1.0 + 323.30000000000001 * exp(-7.333333333333333 - 0.077519379844961239 * Y[0]));
    h_infinity = alpha_h / (alpha_h + beta_h);
    tau_h1 = 0.00014999999999999999 + 0.029999999999999999 / (1.0 + exp(6.666666666666667 + 0.16666666666666666 * Y[0]));
    h1_orig_deriv = (-Y[2] + h_infinity) / tau_h1;
    dY[2] = 0.001 * h1_orig_deriv;
    tau_h2 = 0.00044999999999999999 + 0.12 / (1.0 + exp(30.0 + 0.5 * Y[0]));
    h2_orig_deriv = (-Y[3] + h_infinity) / tau_h2;
    dY[3] = 0.001 * h2_orig_deriv;
    E0_m = 44.399999999999999 + Y[0];
    if (abs(44.399999999999999 + Y[0]) < 1.2672999999963075e-6)
        alpha_m = -0.00058295799999830145 / (-1.0 + exp(-9.9999999999708629e-8)) - 394539.57232025318 * (44.399998732699999 + Y[0]) * (0.00058295799999830145 / (-1.0 + exp(9.9999999999708629e-8)) + 0.00058295799999830145 / (-1.0 + exp(-9.9999999999708629e-8)))
    else 
        alpha_m = -460.0 * (44.399999999999999 + Y[0]) / (-1.0 + exp(-3.5035114021936398 - 0.078907914463820727 * Y[0]))

    beta_m = 18400.0 * exp(-0.078907914463820727 * E0_m);
    if (abs(Y[0]) < 2.6539450910485349e-6)
        i_Na = 188398.77346612973 * (2.6539450910485349e-6 + Y[0]) * (1.8911451999999998e-6 * pow(Y[1], 3) * (-1.0 + exp(9.9999999999999995e-8 - log(140.0 / Y[15]))) * (0.36499999999999999 * Y[3] + 0.63500000000000001 * Y[2]) / (-1.0 + exp(9.9999999999999995e-8)) + 1.8911451999999998e-6 * pow(Y[1], 3) * (-1.0 + exp(-9.9999999999999995e-8 - log(140.0 / Y[15]))) * (0.36499999999999999 * Y[3] + 0.63500000000000001 * Y[2]) / (-1.0 + exp(-9.9999999999999995e-8))) - 1.8911451999999998e-6 * pow(Y[1], 3) * (-1.0 + exp(-9.9999999999999995e-8 - log(140.0 / Y[15]))) * (0.36499999999999999 * Y[3] + 0.63500000000000001 * Y[2]) / (-1.0 + exp(-9.9999999999999995e-8))
    else 
        i_Na = 0.71257887225271721 * pow(Y[1], 3) * (-1.0 + exp(0.037679754693225945 * Y[0] - log(140.0 / Y[15]))) * (0.36499999999999999 * Y[3] + 0.63500000000000001 * Y[2]) * Y[0] / (-1.0 + exp(0.037679754693225945 * Y[0]))

    m_orig_deriv = (1.0 - Y[1]) * alpha_m - Y[1] * beta_m;
    dY[1] = 0.001 * m_orig_deriv;
    i_p = 1.6000000000000001 * pow(Y[15], 1.5) * Y[22] * i_NaK_max / ((1.5 + exp(-1.5 - 0.025000000000000001 * Y[0])) * (pow(Y[15], 1.5) + pow(k_NaK_Na, 1.5)) * (Y[22] + k_NaK_K));
    K_c_orig_deriv = (-2.0 * i_p + i_sus + i_to + i_Kr + i_Ks + i_K1) / (Vol_c * F);
    dY[22] = 0.001 * K_c_orig_deriv;
    K_i_orig_deriv = (-i_sus - i_to - i_Kr - i_Ks - i_K1 + 2.0 * i_p) / (Vol_i * F);
    dY[17] = 0.001 * K_i_orig_deriv;
    Na_i_orig_deriv = (-i_B_Na - i_Na - 3.0 * i_NaCa - 3.0 * i_p) / (Vol_i * F);
    dY[15] = 0.001 * Na_i_orig_deriv;
    V_orig_deriv = -(i_sus + i_to + i_Ca_L + i_NaCa + i_Ca_T + i_B_Ca + i_B_Na + i_Kr + i_Ks + i_inj + i_K1 + i_Stim + i_CaP + i_Na + i_p) / Cm;
    dY[0] = 0.001 * V_orig_deriv;
}

//==============================================================================
// End of file
//==============================================================================
